# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Erin Murphy-Graham
email: emurphy@berkeley.edu
name: Thoughts on international education
description: > # this means to ignore newlines until "baseurl:"
  Webpage of Erin Murphy-Graham, Associate Adjunct Professor of Education at the University
  of California - Berkeley. This website contains information about Professor Murphy-Graham's
  research and teaching activities at UC Berkeley. 
baseurl: "/education"                    # the subpath of your site, e.g. /blog
url: "http://erinmurphygraham.github.io" # the base hostname & protocol for your site
twitter_username: n/a
github_username:  erinmurphygraham

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
highlighter: rouge  